### ISSUE TITLE
Open in apollo with Firefox/chrome

### ISSUE THREAD

**Issue by bilal2vec** [christianselig/OpenInApolloExtension#3]
hiya! love this feature but i doesnt seem to work if your default browser is set to Firefox

**Comment by doamatto** [comment]
Safari extensions in iOS 15 only work in Safari afaik. As far as I know, there aren’t any other browsers have support for extensions on iOS

**Comment by bilal2vec** [comment]
ah makes sense just too bad i guess :*)

**Comment by poxin13** [comment]
There's Orion but it's in beta currently. It can use both firefox/chrome extensions and this one is a key from allowing me to switch to that full time. This +  Amplosion 👍
